# Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd #create data frames(CSV should be converted to structered form)
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.tests import TfidfVectorizer # convert text data into numerical data
# from sklearn.linear_model import logisticRegression
# from sklearn.metrics import accuracy_score #test data is used to test the model- to find the accuarcy needs

Data Collection and Preprocessing

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"
url_names = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.names"

data = pd.read_csv(url,header=None)

data.head()

0     1     2    3     4     5     6     7     8     9   ...    48  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   

      49   50     51     52     53     54   55    56  57  
0  0.000  0.0  0.778  0.000  0.000  3.756   61   278   1  
1  0.132  0.0  0.372  0.180  0.048  5.114  101  1028   1  
2  0.143  0.0  0.276  0.184  0.010  9.821  485  2259   1  
3  0.137  0.0  0.137  0.000  0.000  3.537   40   191   1  
4  0.135  0.0  0.135  0.000  0.000  3.537   40   191   1  

[5 rows x 58 columns]

In [4]:
data.shape

(4601, 58)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       4601 non-null   float64
 1   1       4601 non-null   float64
 2   2       4601 non-null   float64
 3   3       4601 non-null   float64
 4   4       4601 non-null   float64
 5   5       4601 non-null   float64
 6   6       4601 non-null   float64
 7   7       4601 non-null   float64
 8   8       4601 non-null   float64
 9   9       4601 non-null   float64
 10  10      4601 non-null   float64
 11  11      4601 non-null   float64
 12  12      4601 non-null   float64
 13  13      4601 non-null   float64
 14  14      4601 non-null   float64
 15  15      4601 non-null   float64
 16  16      4601 non-null   float64
 17  17      4601 non-null   float64
 18  18      4601 non-null   float64
 19  19      4601 non-null   float64
 20  20      4601 non-null   float64
 21  21      4601 non-null   float64
 22  

In [7]:
#divide into x and y data
x = data.iloc[:,0:-1].values

In [8]:
y = data.iloc[:,-1].values

In [10]:
# Splitting the data set  into training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25, random_state=None, shuffle=True)

In [11]:
# Feature scaling - a method used to normalize the range of independent variables or features of data.
# It normalizes data within a certain range
from sklearn.preprocessing import StandardScaler

ssc = StandardScaler()
x_train = ssc.fit_transform(x_train)
x_test = ssc.fit_transform(x_test)

In [19]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knclassifier = KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2) # p- power parameter # metric-metrics used for distance computation
# minkowski- euclidean distance

knclassifier.fit(x_train,y_train) #fitting classifier to the training set
y_knn_predic = knclassifier.predict(x_test) # predicting the test set results

C:\Users\lisar\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [20]:
print (y_knn_predic[0:5])
print (y_test[0:5])
# to visually compare the prediction to the actual values

[0 1 1 1 0]
[0 1 1 1 0]


In [21]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
dtclassifier = DecisionTreeClassifier(random_state=0)
dtclassifier.fit(x_train,y_train) #fitting the classifier to the training data set
y_dtc_predic = dtclassifier.predict(x_test)

In [22]:
print (y_dtc_predic[0:5])
print (y_test[0:5])

[0 1 1 1 0]
[0 1 1 1 0]


## Evaluation

Let's check the accuracy of the models

In [23]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("KNN Accuracy: ", metrics.accuracy_score(y_test,y_knn_predic))
print("Decision Tree Accuracy: ", metrics.accuracy_score(y_test,y_dtc_predic))

KNN Accuracy:  0.9035621198957429
Decision Tree Accuracy:  0.8844483058210252


## Visualization

In [ ]:
from six import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn import tree
%matplotlib inline#%% md
# Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd #create data frames(CSV should be converted to structered form)
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.tests import TfidfVectorizer # convert text data into numerical data
# from sklearn.linear_model import logisticRegression
# from sklearn.metrics import accuracy_score #test data is used to test the model- to find the accuarcy needs

Data Collection and Preprocessing

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"
url_names = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.names"

data = pd.read_csv(url,header=None)

data.head()

In [ ]:
data.shape

In [ ]:
data.info()

In [ ]:
#divide into x and y data
x = data.iloc[:,0:-1].values

In [ ]:
y = data.iloc[:,-1].values

In [ ]:
# Splitting the data set  into training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25, random_state=None, shuffle=True)

In [ ]:
# Feature scaling - a method used to normalize the range of independent variables or features of data.
# It normalizes data within a certain range
from sklearn.preprocessing import StandardScaler

ssc = StandardScaler()
x_train = ssc.fit_transform(x_train)
x_test = ssc.fit_transform(x_test)

In [ ]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knclassifier = KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2) # p- power parameter # metric-metrics used for distance computation
# minkowski- euclidean distance

knclassifier.fit(x_train,y_train) #fitting classifier to the training set
y_knn_predic = knclassifier.predict(x_test) # predicting the test set results

In [ ]:
print (y_knn_predic[0:5])
print (y_test[0:5])
# to visually compare the prediction to the actual values

In [ ]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
dtclassifier = DecisionTreeClassifier(random_state=0)
dtclassifier.fit(x_train,y_train) #fitting the classifier to the training data set
y_dtc_predic = dtclassifier.predict(x_test)

In [ ]:
print (y_dtc_predic[0:5])
print (y_test[0:5])

## Evaluation

Let's check the accuracy of the models

In [ ]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("KNN Accuracy: ", metrics.accuracy_score(y_test,y_knn_predic))
print("Decision Tree Accuracy: ", metrics.accuracy_score(y_test,y_dtc_predic))

## Visualization

In [1]:
from six import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn import tree
%matplotlib inline

ModuleNotFoundError: No module named 'pydotplus'

In [ ]:
dot_data = StringIO()
filename = "spamtree.png"

featureNames = data.columns[0:57]
# targetNames = data["Drug"].unique().tolist()

out=tree.export_graphviz(dtclassifier,feature_names=featureNames,
                         out_file=dot_data,
                         class_names= ["ham", "spam"],
                         filled=True,
                         special_characters=True,
                         rotate=False)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png(filename)
img = mpimg.imread(filename)

plt.figure(figsize=(100, 200))
plt.imshow(img,interpolation='nearest')

In [ ]:
from matplotlib import pyplot as plt # Visualize the training data set results
from matplotlib.colors import ListedColormap # used to create a custom color map for the plot

x_set, y_set= x_train, y_train #assign values which are used to create a grid of points for the plot
x1,x2= np.meshgrid(np.arange(start=x_set[:,0].min()-1,stop=x_set[:,0].max()+1, step = 0.01),np.arange(start=x_set[:,1].min()-1,stop=x_set[:,1].max()+1, step = 0.01))
plt.contourf(x1, x2, knclassifier.predict(np.array([x1.ravel(),x2.ravel()]).T).reshape(x1.shape),alpha=0.75, cmap = ListedColormap(('pink','green')))
plt.xlim(x1.min(),x1.max())
plt.ylim(x1.min(),x1.max())

In [15]:
from matplotlib import pyplot as plt
# Visualize the training data set results

from matplotlib.colors import ListedColormap
# used to create a custom color map for the plot

x_set, y_set= x_train, y_train #assign values which are used to create a grid of points for the plot

x1,x2= np.meshgrid(np.arange(start=x_set[:,0].min()-1,stop=x_set[:,0].max()+1, step = 0.01),np.arange(start=x_set[:,1].min()-1,stop=x_set[:,1].max()+1, step = 0.01))
plt.contourf(x1, x2, knclassifier.predict(np.array([x1.ravel(),x2.ravel()]).T).reshape(x1.shape),alpha=0.75, cmap = ListedColormap(('pink','green')))
plt.xlim(x1.min(),x1.max())
plt.ylim(x1.min(),x1.max())


ValueError: X has 2 features, but KNeighborsClassifier is expecting 57 features as input.